name: main-workflow

on:
  pull_request:
<<<<<<< HEAD
    branches: main
=======
    branches: master
>>>>>>> ca2a5ef (change2)

jobs:
  setup:
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}