name: main-workflow

on:
  pull_request:
    branches: master
    types: [synchronize]

jobs:
  setup:
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}