name: main-workflow

on:
  pull_request:
    branches: main

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Tryouts 2
        run: |
          statuses="$(gh api /repos/QadricRosa/sandbox/statuses/a2ca8383a3006edb7b67270a1da36fae41de1651 --jq '.')"

          echo $statuses

          statusNb=$("statuses" | jq --jsonargs 'length')

          echo $statusNb
