name: Argos update check

on:
  status

jobs:
  status-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: output logs
        id: statuses
        run: |
          echo ${{ toJSON(github.event) }}
          echo ${{ github.event.commit.sha }}