name: Argos update check

on:
  status

jobs:
  status-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: output logs
        id: statuses
        run: |
          echo ${{ github.event.creator.id }}
          echo ${{ github.event.state }}
          echo ${{ github.event.commit }}