name: Argos update check

on:
  status

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  status-workflow-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.id == 93592207 && contains(fromJSON('["success", "failure"]'), github.event.state) }}
    steps:
      - name: Retrieve state
        id: status
        run: |
          echo ${{ github.event.sha }}
          
          state="$(gh api /repos/QadricRosa/sandbox/commits/${{ github.event.sha }}/status --jq '.state')"

          echo state="$state" >> $GITHUB_OUTPUT

      - name: Fail check
        uses: LouisBrunner/checks-action@v1.6.0
        if: ${{ steps.status.outputs.state == 'failure' }}
        with:
          sha: ${{ github.event.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Added checks
          conclusion: ${{ steps.status.outputs.state }}
          output: |
            {
              "title":"Failing checks",
              "summary":"Failing checks, please verify the failing checks and provide a follow-up commit to solve them"
            }
        
      - name: Success check
        uses: LouisBrunner/checks-action@v1.6.0
        if: ${{ steps.status.outputs.state == 'success' }}
        with:
          sha: ${{ github.event.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Added checks
          conclusion: ${{ steps.status.outputs.state }}
          output: |
            {
              "title":"All green!",
              "summary":"All checks have passed, merge can proceed"
            }
