name: sub-workflow

on:
  workflow_run:
    workflows: [main-workflow]
    types:
      - completed

jobs:
  check_and_follow_up:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - run: git branch

      - name: Get main pr_number & pr_head_sha
        id: checks
        run: |
          pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
          pr_head_sha="${{ github.event.workflow_run.pull_requests[0].head.sha }}"

          echo pr_number
          echo pr_head_sha
          echo change 9

          echo summary="PR checks passed!\n" >> $GITHUB_OUTPUT
          echo state="pending" >> $GITHUB_OUTPUT

      - uses: LouisBrunner/checks-action@v1.6.0
        if: always() && ${{ steps.checks.outputs.state == 'pending' }}
        with:
          sha: ${{ github.event.workflow_run.pull_requests[0].head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Added checks
          conclusion: ${{ job.status }}
          output: |
            {
              "title":"${{ steps.checks.outputs.summary }}",
              "summary":"${{ steps.checks.outputs.summary }}"
            }
